# Generated by Django 3.1.1 on 2020-09-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='write_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('create_data', models.DateField(blank=True, null=True)),
                ('area', models.CharField(blank=True, choices=[('Seoul', '서울특별시'), ('Incheon', '인천광역시'), ('Gyeonggi-do', '경기도'), ('Gangwon-do', '강원도'), ('Chungcheongnam-do', '충청남도'), ('Sejong', '세종특별자치시'), ('Daejeon', '대전광역시'), ('Chungcheongbuk-do', '충청북도'), ('Gyeongsangbuk-do', '경상북도'), ('Gyeongsangnam-do', '경상남도'), ('Daegu', '대구광역시'), ('Jeollabuk-do', '전라북도'), ('Jeollanam-do', '전라남도'), ('Gwangju', '광주광역시'), ('Ulsan', '울산광역시'), ('Busan', '부산광역시'), ('Jeju', '제주특별자치시도')], max_length=17, null=True)),
                ('start_data', models.DateField(blank=True, null=True)),
                ('end_data', models.DateField(blank=True, null=True)),
                ('voluteer_type', models.CharField(blank=True, choices=[('type_1', '자연환경보호활동'), ('type_2', '지역사회봉사활동'), ('type_3', '기술지원'), ('type_4', '업무보조'), ('type_5', '정서지원'), ('type_6', '기타봉사'), ('type_7', '생활지원'), ('type_8', '전문봉사')], max_length=8, null=True)),
                ('how_many', models.IntegerField(blank=True, null=True)),
                ('mainphoto', models.ImageField(blank=True, null=True, upload_to='')),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('hits', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('mail', models.CharField(blank=True, max_length=50)),
                ('phone_num', models.CharField(max_length=30)),
                ('affiliation', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentPost',
        ),
        migrations.DeleteModel(
            name='volunteer_lst',
        ),
    ]
