# Generated by Django 3.1.1 on 2020-09-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20200924_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write_post',
            name='affiliation',
            field=models.CharField(blank=True, choices=[('volunteer', '자원봉사자'), ('agency', '기관')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='write_post',
            name='memo',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
