# Generated by Django 3.1.1 on 2020-09-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20200924_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='write_post',
            old_name='create_data',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='write_post',
            name='end_data',
        ),
        migrations.RemoveField(
            model_name='write_post',
            name='start_data',
        ),
    ]
