# Generated by Django 3.1.1 on 2020-09-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20200924_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='write_post',
            old_name='data',
            new_name='term',
        ),
    ]
