# Generated by Django 3.1.1 on 2020-09-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20200924_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='write_post',
            old_name='voluteer_type',
            new_name='volunteer_type',
        ),
    ]
