# Generated by Django 3.1.1 on 2020-09-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20200924_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='write_post',
            old_name='mainphoto',
            new_name='photo',
        ),
    ]
