# Generated by Django 3.1.1 on 2020-09-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20200924_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='write_post',
            old_name='mail',
            new_name='email',
        ),
    ]
