# Generated by Django 3.1.1 on 2020-09-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20200924_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write_post',
            name='term',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
