# Generated by Django 3.1.1 on 2020-09-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_auto_20200924_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='write_post',
            old_name='memo',
            new_name='memo1',
        ),
        migrations.AddField(
            model_name='write_post',
            name='memo2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='write_post',
            name='memo3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='write_post',
            name='affiliation',
            field=models.CharField(blank=True, default=1, max_length=30),
            preserve_default=False,
        ),
    ]
